GET http://localhost:3004/workers HTTP/1.1

###

POST http://localhost:3004/workers HTTP/1.1
content-Type: application/json

{
    "role": "worker",
    "first_name": "Diego",
    "last_name": "López",
    "photo": "http://dummyimage.com/109x193.bmp/cc0000/ffffff",
    "services": ["Web Developer I"]
}